# Generated by Django 5.1.7 on 2025-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dilemma_game', '0002_tournament_tournamentparticipant_tournamentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_rounds',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_rounds',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='use_random_rounds',
            field=models.BooleanField(default=False),
        ),
    ]
