# Generated by Django 5.1.7 on 2025-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dilemma_game', '0003_tournament_max_rounds_tournament_min_rounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
