# Generated by Django 5.1.7 on 2025-06-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dilemma_game', '0002_add_win_loss_fields'),
        ('dilemma_game', '0004_tournamentparticipant_draws_and_more'),
    ]

    operations = [
    ]
