# Generated by Django 5.1.7 on 2025-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dilemma_game', '0006_strategy_is_preset_strategy_preset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='continue_probability',
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name='tournament',
            name='use_probability_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
