# Generated by Django 5.1.7 on 2025-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dilemma_game', '0007_tournament_continue_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='actual_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
